### ISSUE TITLE
eu.dime.ps.storage.StorageException: 35 on POST [..]1/context/@me

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#12]
This was working previously - I don't know where it comes from.

(Caused by: java.lang.ArrayIndexOutOfBoundsException: 35)

When posting 

Request URL:https://127.0.0.1:8443/dime-communications/api/dime/rest/dummy7001/context/@me
Request Method:POST
Status Code:200 OK
Request Headersview source
Accept:application/json, text/javascript, _/_; q=0.01
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8,de-DE;q=0.6,de;q=0.4,en-GB;q=0.2
Cache-Control:no-cache
Connection:keep-alive
Content-Length:491
Content-Type:application/json; charset=UTF-8
Cookie:JSESSIONID=C87B8FAB50716548005CD80ACDB7AE44
Host:127.0.0.1:8443
Origin:https://127.0.0.1:8443
Pragma:no-cache
Referer:https://127.0.0.1:8443/dime-communications/static/ui/dime/index.html?vT=1&gT=place&pG=%40me
User-Agent:Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.71 Chrome/28.0.1500.71 Safari/537.36
X-Requested-With:XMLHttpRequest
Request Payloadview source
{request:{meta:{v:0.9, status:OK, code:200, timeRef:1381836069529},…}}
request: {meta:{v:0.9, status:OK, code:200, timeRef:1381836069529},…}
Response Headersview source
Content-Type:application/json;charset=UTF-8
Date:Tue, 15 Oct 2013 11:21:09 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

{"request":{"meta":{"v":"0.9","status":"OK","code":200,"timeRef":1381836069529},"data":{"startIndex":0,"itemsPerPage":1,"totalResults":1,"entry":[{"guid":"eb71bff-8298-9ca4-332f-9faaa4ec9df0","type":"context","timestamp":"2013-10-15T11:21:09+02:00","expires":"2013-10-15T21:59:59+02:00","scope":"position","entity":{"id":"@me","type":"username"},"source":{"id":"desktop-crawler","v":"0.9"},"dataPart":{"latitude":48.775417999999995,"longitude":9.181759,"accuracy":18000,"locMode":"NET"}}]}}}

{"response":{"meta":{"status":"ERROR","code":400,"timeRef":1381836069599,"v":"0.9","msg":"contextUpdate exception: 35"}}}

Server log:

2013-10-15 13:21:09 ContextProcessorImpl [ERROR] eu.dime.ps.storage.StorageException: 35
eu.dime.ps.storage.StorageException: 35
        at eu.dime.ps.storage.DimeStorageImpl.storeContextElement(DimeStorageImpl.java:116)
        at eu.dime.ps.contextprocessor.impl.ContextProcessorImpl.contextUpdate(ContextProcessorImpl.java:119)
        at eu.dime.ps.controllers.context.raw.impl.RawContextManagerImpl.contextUpdate(RawContextManagerImpl.java:120)
        at eu.dime.ps.communications.requestbroker.controllers.context.PSContextController.postMyContext(PSContextController.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:368)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:97)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:100)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:78)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:35)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:177)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:187)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:79)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:169)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at eu.dime.ps.communications.filter.TenantSetFilter.doFilter(TenantSetFilter.java:79)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at eu.dime.ps.communications.filter.AccessFilter.doFilter(AccessFilter.java:127)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 35
        at com.db4o.internal.ByteArrayBuffer.readInt(ByteArrayBuffer.java:147)
        at com.db4o.internal.PersistentIntegerArray.readThis(PersistentIntegerArray.java:44)
        at com.db4o.internal.PersistentBase.read(PersistentBase.java:50)
        at com.db4o.internal.PersistentBase.read(PersistentBase.java:40)
        at com.db4o.internal.ids.BTreeIdSystem.initializeExisting(BTreeIdSystem.java:65)
        at com.db4o.internal.ids.BTreeIdSystem.<init>(BTreeIdSystem.java:50)
        at com.db4o.internal.ids.BTreeIdSystem.<init>(BTreeIdSystem.java:60)
        at com.db4o.internal.ids.StandardIdSystemFactory.newInstance(StandardIdSystemFactory.java:41)
        at com.db4o.internal.LocalObjectContainer.createIdSystem(LocalObjectContainer.java:534)
        at com.db4o.internal.LocalObjectContainer.readThis(LocalObjectContainer.java:479)
        at com.db4o.internal.IoAdaptedObjectContainer.openImpl(IoAdaptedObjectContainer.java:71)
        at com.db4o.internal.ObjectContainerBase$1.run(ObjectContainerBase.java:140)
        at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
        at com.db4o.foundation.Environments.runWith(Environments.java:28)
        at com.db4o.internal.ObjectContainerBase.withEnvironment(ObjectContainerBase.java:161)
        at com.db4o.internal.ObjectContainerBase.open(ObjectContainerBase.java:131)
        at com.db4o.internal.IoAdaptedObjectContainer.<init>(IoAdaptedObjectContainer.java:35)
        at com.db4o.internal.ObjectContainerFactory.openObjectContainer(ObjectContainerFactory.java:18)
        at com.db4o.Db4o.openFile(Db4o.java:223)
        at com.db4o.cs.internal.config.StandardClientServerFactory.openServer(StandardClientServerFactory.java:35)
        at com.db4o.cs.Db4oClientServer.openServer(Db4oClientServer.java:52)
        at eu.dime.ps.storage.datastore.engine.Db4oPersistenceEngine.openConnection(Db4oPersistenceEngine.java:102)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.createTenantStore(DataStoreProvider.java:61)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.getTenantStore(DataStoreProvider.java:54)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.getTenantStore(DataStoreProvider.java:89)
        at eu.dime.ps.storage.DimeStorageImpl.getDataStore(DimeStorageImpl.java:62)
        at eu.dime.ps.storage.DimeStorageImpl.storeContextElement(DimeStorageImpl.java:108)
        ... 78 more
2013-10-15 13:21:09 PSContextController [ERROR] contextUpdate exception: 35
eu.dime.context.exceptions.ContextException: contextUpdate exception: 35
        at eu.dime.ps.contextprocessor.impl.ContextProcessorImpl.contextUpdate(ContextProcessorImpl.java:128)
        at eu.dime.ps.controllers.context.raw.impl.RawContextManagerImpl.contextUpdate(RawContextManagerImpl.java:120)
        at eu.dime.ps.communications.requestbroker.controllers.context.PSContextController.postMyContext(PSContextController.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:368)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:97)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:100)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:78)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:35)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:177)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:187)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:79)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:109)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:380)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:169)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at eu.dime.ps.communications.filter.TenantSetFilter.doFilter(TenantSetFilter.java:79)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at eu.dime.ps.communications.filter.AccessFilter.doFilter(AccessFilter.java:127)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:722)
Caused by: eu.dime.ps.storage.StorageException: 35
        at eu.dime.ps.storage.DimeStorageImpl.storeContextElement(DimeStorageImpl.java:116)
        at eu.dime.ps.contextprocessor.impl.ContextProcessorImpl.contextUpdate(ContextProcessorImpl.java:119)
        ... 77 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 35
        at com.db4o.internal.ByteArrayBuffer.readInt(ByteArrayBuffer.java:147)
        at com.db4o.internal.PersistentIntegerArray.readThis(PersistentIntegerArray.java:44)
        at com.db4o.internal.PersistentBase.read(PersistentBase.java:50)
        at com.db4o.internal.PersistentBase.read(PersistentBase.java:40)
        at com.db4o.internal.ids.BTreeIdSystem.initializeExisting(BTreeIdSystem.java:65)
        at com.db4o.internal.ids.BTreeIdSystem.<init>(BTreeIdSystem.java:50)
        at com.db4o.internal.ids.BTreeIdSystem.<init>(BTreeIdSystem.java:60)
        at com.db4o.internal.ids.StandardIdSystemFactory.newInstance(StandardIdSystemFactory.java:41)
        at com.db4o.internal.LocalObjectContainer.createIdSystem(LocalObjectContainer.java:534)
        at com.db4o.internal.LocalObjectContainer.readThis(LocalObjectContainer.java:479)
        at com.db4o.internal.IoAdaptedObjectContainer.openImpl(IoAdaptedObjectContainer.java:71)
        at com.db4o.internal.ObjectContainerBase$1.run(ObjectContainerBase.java:140)
        at com.db4o.foundation.DynamicVariable.with(DynamicVariable.java:54)
        at com.db4o.foundation.Environments.runWith(Environments.java:28)
        at com.db4o.internal.ObjectContainerBase.withEnvironment(ObjectContainerBase.java:161)
        at com.db4o.internal.ObjectContainerBase.open(ObjectContainerBase.java:131)
        at com.db4o.internal.IoAdaptedObjectContainer.<init>(IoAdaptedObjectContainer.java:35)
        at com.db4o.internal.ObjectContainerFactory.openObjectContainer(ObjectContainerFactory.java:18)
        at com.db4o.Db4o.openFile(Db4o.java:223)
        at com.db4o.cs.internal.config.StandardClientServerFactory.openServer(StandardClientServerFactory.java:35)
        at com.db4o.cs.Db4oClientServer.openServer(Db4oClientServer.java:52)
        at eu.dime.ps.storage.datastore.engine.Db4oPersistenceEngine.openConnection(Db4oPersistenceEngine.java:102)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.createTenantStore(DataStoreProvider.java:61)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.getTenantStore(DataStoreProvider.java:54)
        at eu.dime.ps.storage.datastore.impl.DataStoreProvider.getTenantStore(DataStoreProvider.java:89)
        at eu.dime.ps.storage.DimeStorageImpl.getDataStore(DimeStorageImpl.java:62)
        at eu.dime.ps.storage.DimeStorageImpl.storeContextElement(DimeStorageImpl.java:108)
        ... 78 more
2013-10-15 13:21:09 Response [ERROR] contextUpdate exception: 35: contextUpdate exception: 35

**Comment by thielsn** [comment]
This is caused by a CMS issue and caused by some known robustness problems with restarting the server.
