### ISSUE TITLE
(internal) sharing of livepost not working after update of server

### ISSUE THREAD

**Issue by christian-knecht** [dime-project/meta#13]
git commit:  bee48432b91534909731f719c7801703699bd104

Server Log:

Okt 18, 2013 12:10:23 PM eu.dime.ps.communications.requestbroker.controllers.infosphere.PSLivePostController createLivePost
INFO: called API method: POST /dime/rest/dummy2003/livepost/@me
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a notification in the storage: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"create","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","unEntry":null,"createTS":1382091023936,"updateTS":1382091023936,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a System Notification in the queue: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"create","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","unEntry":null,"createTS":1382091023936,"updateTS":1382091023936,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a notification in the storage: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"create","itemType":"livepost","itemID":"urn:uuid:09ac1ea8-0c77-4a2f-a7eb-2c7bc74b4ce6","unEntry":null,"createTS":1382091023939,"updateTS":1382091023939,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a System Notification in the queue: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"create","itemType":"livepost","itemID":"urn:uuid:09ac1ea8-0c77-4a2f-a7eb-2c7bc74b4ce6","unEntry":null,"createTS":1382091023939,"updateTS":1382091023939,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a notification in the storage: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"update","itemType":"livepost","itemID":"urn:uuid:09ac1ea8-0c77-4a2f-a7eb-2c7bc74b4ce6","unEntry":null,"createTS":1382091023943,"updateTS":1382091023943,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a System Notification in the queue: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"systemnotification","operation":"update","itemType":"livepost","itemID":"urn:uuid:09ac1ea8-0c77-4a2f-a7eb-2c7bc74b4ce6","unEntry":null,"createTS":1382091023943,"updateTS":1382091023943,"isRead":null,"userID":"@me"}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushExternalNotification
INFO: Addind a notification in the queue: {"id":null,"target":"urn:uuid:55a537ea-5b94-412e-a75f-9cae441afcb0","sender":"urn:uuid:fdec2e58-6fd7-445f-8ce0-7ce1bced51e7","notificationType":null,"operation":"share","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","name":null,"tenant":14,"userID":null}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushExternalNotification
INFO: Addind a notification in the queue: {"id":null,"target":"urn:uuid:55a537ea-5b94-412e-a75f-9cae441afcb0","sender":"urn:uuid:fdec2e58-6fd7-445f-8ce0-7ce1bced51e7","notificationType":null,"operation":"share","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","name":null,"tenant":14,"userID":null}
Okt 18, 2013 12:10:23 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a notification in the storage: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"usernotification","operation":null,"itemType":null,"itemID":null,"unEntry":{"guid":"urn:uuid:67434c90-fa84-44d7-b641-c01faeaa6c93","unType":"ref_to_item","operation":"inc_trust","name":"dummy dummy","userId":"@me","type":"person"},"createTS":1382091023987,"updateTS":1382091023987,"isRead":false,"userID":"@me"}
Okt 18, 2013 12:10:24 PM eu.dime.ps.controllers.notifier.impl.NotifierManagerImpl pushInternalNotification
INFO: Addind a User Notification in the queue: {"id":null,"name":"Notification","tenant":14,"target":"@me","sender":"@me","notificationType":"usernotification","operation":null,"itemType":null,"itemID":null,"unEntry":{"guid":"urn:uuid:67434c90-fa84-44d7-b641-c01faeaa6c93","unType":"ref_to_item","operation":"inc_trust","name":"dummy dummy","userId":"@me","type":"person"},"createTS":1382091023987,"updateTS":1382091023987,"isRead":false,"userID":"@me"}
Okt 18, 2013 12:10:24 PM eu.dime.ps.communications.notifier.ExternalNotifySchedule dealNotifications
INFO: Notification dealed to DimeServiceAdapter ({"id":null,"target":"urn:uuid:55a537ea-5b94-412e-a75f-9cae441afcb0","sender":"urn:uuid:fdec2e58-6fd7-445f-8ce0-7ce1bced51e7","notificationType":null,"operation":"share","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","name":null,"tenant":14,"userID":null})
Okt 18, 2013 12:10:24 PM eu.dime.ps.gateway.proxy.HttpRestProxy post
INFO: Performing POST https://dime.hci.iao.fraunhofer.de:8443/dime-communications/api/services/dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443/set/notification HTTP/1.1
Payload:{"request":{"data":{"startIndex":0,"itemsPerPage":0,"totalResults":0,"entry":[{"guid":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","type":"notification","sender":"fdec2e58-6fd7-445f-8ce0-7ce1bced51e7@dime.hci.iao.fraunhofer.de:8443","operation":"share","date":0,"saidSender":"fdec2e58-6fd7-445f-8ce0-7ce1bced51e7@dime.hci.iao.fraunhofer.de:8443","saidReciever":"dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443","element":{"guid":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","type":"livepost"}}]}}}
Okt 18, 2013 12:10:24 PM eu.dime.commons.dto.Response serverError
SEVERE: Unknown Error! Details: Could not find neither a tenant nor a service account with name 'dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443'.
eu.dime.ps.controllers.exception.TenantManagerException: Could not find neither a tenant nor a service account with name 'dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443'.
        at eu.dime.ps.controllers.TenantManagerImpl.getByAccountName(TenantManagerImpl.java:65)
        at eu.dime.ps.communications.requestbroker.controllers.servicegateway.PSServicesController.setNotification(PSServicesController.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)

Okt 18, 2013 12:10:25 PM eu.dime.ps.communications.notifier.ExternalNotifySchedule dealNotifications
INFO: Notification dealed to DimeServiceAdapter ({"id":null,"target":"urn:uuid:55a537ea-5b94-412e-a75f-9cae441afcb0","sender":"urn:uuid:fdec2e58-6fd7-445f-8ce0-7ce1bced51e7","notificationType":null,"operation":"share","itemType":"livepost","itemID":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","name":null,"tenant":14,"userID":null})
Okt 18, 2013 12:10:25 PM eu.dime.ps.gateway.proxy.HttpRestProxy post
INFO: Performing POST https://dime.hci.iao.fraunhofer.de:8443/dime-communications/api/services/dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443/set/notification HTTP/1.1
Payload:{"request":{"data":{"startIndex":0,"itemsPerPage":0,"totalResults":0,"entry":[{"guid":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","type":"notification","sender":"fdec2e58-6fd7-445f-8ce0-7ce1bced51e7@dime.hci.iao.fraunhofer.de:8443","operation":"share","date":0,"saidSender":"fdec2e58-6fd7-445f-8ce0-7ce1bced51e7@dime.hci.iao.fraunhofer.de:8443","saidReciever":"dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443","element":{"guid":"urn:uuid:2aa275fb-126a-444b-8e22-988c1011db31","type":"livepost"}}]}}}
Okt 18, 2013 12:10:25 PM eu.dime.commons.dto.Response serverError
SEVERE: Unknown Error! Details: Could not find neither a tenant nor a service account with name 'dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443'.
eu.dime.ps.controllers.exception.TenantManagerException: Could not find neither a tenant nor a service account with name 'dime:urs05a6a907-ec1f-4fae-a941-87843cdd5528@dime.hci.iao.fraunhofer.de:8443'.
        at eu.dime.ps.controllers.TenantManagerImpl.getByAccountName(TenantManagerImpl.java:65)
        at eu.dime.ps.communications.requestbroker.controllers.servicegateway.PSServicesController.setNotification(PSServicesController.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:929)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1002)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:585)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)

**Comment by christian-knecht** [comment]
it seems to be an issue of the dime user directory. sharing to the team server is working. wrong said?
said: dime:ursb12bd469-cfb0-4e16-9b5f-b3e52dc455cb@dime.hci.iao.fraunhofer.de:8443

**Comment by thielsn** [comment]
fixed - on the PRS
