### ISSUE TITLE
Test fails: eu.dime.ps.semantic.service.PimoServiceTest

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#23]
## Test set: eu.dime.ps.semantic.service.PimoServiceTest

Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.931 sec <<< FAILURE!
testPimoCreation(eu.dime.ps.semantic.service.PimoServiceTest)  Time elapsed: 0.377 sec  <<< FAILURE!
java.lang.AssertionError: 
        at org.junit.Assert.fail(Assert.java:91)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertFalse(Assert.java:68)
        at org.junit.Assert.assertFalse(Assert.java:79)
        at eu.dime.ps.semantic.service.PimoServiceTest.testPimoCreation(PimoServiceTest.java:71)

**Comment by ismriv** [comment]
Issue fixed on https://github.com/dime-project/dime-server/commit/c404f31cd6f12036862bd1594ccce7c870868e22
