### ISSUE TITLE
di.me server not working on some windows machines (registration fails)

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#29]
"Cannot find user configuration in config-repository. Missing an instance of serverconfig:User with required properties. Dump:"

when trying to register the following exception appears in the log:
(however the user is added in the db - so a second try gives a different error about the already existing user...)

2013-11-26 14:03:59 DispatcherServlet [INFO] FrameworkServlet 'dime-web-pages': initialization completed in 695 ms
Nov 26, 2013 2:03:59 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8080
Nov 26, 2013 2:03:59 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8080
Nov 26, 2013 2:03:59 PM org.apache.coyote.http11.Http11Protocol init
INFO: Initializing Coyote HTTP/1.1 on http-8443
Nov 26, 2013 2:03:59 PM org.apache.coyote.http11.Http11Protocol start
INFO: Starting Coyote HTTP/1.1 on http-8443
2013-11-26 14:04:07 PurgeNotifySchedule [INFO] Queues purge executed.
2013-11-26 14:04:07 NotifyFIFOMultiTenant [INFO] Purging deprecated Notifications
2013-11-26 14:04:15 SesameMemoryRepositoryFactory [INFO] RDF repository at C:\Users\pgrau.dime\rdf\2 [syncDelay=5000, inferencing=true]
2013-11-26 14:04:15 SesameMemoryRepositoryFactory [INFO] RDF repository at C:\Users\pgrau.dime\rdf\2 [syncDelay=5000, inferencing=true]
2013-11-26 14:04:15 PimoService [INFO] Setting up PIMO Service
2013-11-26 14:04:15 PimoService [INFO] Setting up PIMO Service
2013-11-26 14:04:15 SituationDetector [ERROR] Couldn't access RDF services of tenant with id 2
2013-11-26 14:04:15 SesameMemoryRepositoryFactory [INFO] RDF repository at C:\Users\pgrau.dime\rdf\1 [syncDelay=5000, inferencing=true]
2013-11-26 14:04:15 TimePeriodUpdater [ERROR] Cannot access RDF repository for tenant '2': eu.dime.ps.semantic.service.exception.PimoConfigurationException: Cannot find user configuration in config-repository. Missing an instance of serverconfig:User with required properties. Dump:

org.openrdf.repository.RepositoryException: eu.dime.ps.semantic.service.exception.PimoConfigurationException: Cannot find user configuration in config-repository. Missing an instance of serverconfig:User with required properties. Dump:

```
    at eu.dime.ps.semantic.connection.Connection.getPimoService(Connection.java:117)
    at eu.dime.ps.semantic.connection.Connection.getLiveContextService(Connection.java:131)
    at eu.dime.ps.controllers.context.TimePeriodUpdater.update(TimePeriodUpdater.java:83)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
```

**Comment by thielsn** [comment]
the error message shown above is the wrong error - since it was triggered by the at eu.dime.ps.controllers.context.TimePeriodUpdater.update(TimePeriodUpdater.java:83)
and not from createTenant which would be the one for the registration

The TimePeriodUpdater will try again later - however, it's potentially a problem with simultaneously accessing the file...

![createtenant](https://f.cloud.github.com/assets/4115477/1622759/9ac21f16-56aa-11e3-8094-c3a12f67e0d3.png)

**Comment by thielsn** [comment]
Since the error message was due to another issue - I'll close the bug and create a new one.
