### ISSUE TITLE
di.me server not working on some machines (registration fails)

### ISSUE THREAD

**Issue by thielsn** [dime-project/meta#30]
DimeUserResolverServiceAdapter
java.io.IOException: Registration failed. Could not parse server response.

(see below)

Even though it was tested by Richard that the server was reachable and the response should be ok. 

Assumption - misleading error message.

On the system we tested with Windows MySQL server - there seems also to be a problem with the db connector:

2013-11-26 16:10:10 JdbcSupportLoader [INFO] Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2013-11-26 16:10:10 SettingsFactory [INFO] Database ->
       name : MySQL
    version : 5.6.11
      major : 5
      minor : 6
2013-11-26 16:10:10 SettingsFactory [INFO] Driver ->
       name : MySQL-AB JDBC Driver
    version : mysql-connector-java-5.1.17 ( Revision: ${bzr.revision-id} )
      major : 5
      minor : 1

[...]

013-11-26 16:11:23 DimeUserResolverServiceAdapter [ERROR] java.io.IOException: Registration failed. Could not parse server response.
java.io.IOException: Registration failed. Could not parse server response.
        at eu.dime.ps.gateway.service.external.DimeUserResolverServiceAdapter.registerAtURS(DimeUserResolverServiceAdapter.java:283)
        at eu.dime.ps.gateway.service.external.DimeUserResolverServiceAdapter._set(DimeUserResolverServiceAdapter.java:142)
        at eu.dime.ps.gateway.service.ServiceAdapterBase.set(ServiceAdapterBase.java:214)
        at eu.dime.ps.controllers.UserManagerImpl.registerToUserResolverService(UserManagerImpl.java:385)
        at eu.dime.ps.controllers.UserManagerImpl.register(UserManagerImpl.java:454)
        at eu.dime.ps.communications.requestbroker.controllers.register.PSUserController.createUser(PSUserController.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:724)
2013-11-26 16:11:23 UserManagerImpl [ERROR] eu.dime.commons.exception.DimeException: Failed to register at dime user register service. Aborting registration.
eu.dime.commons.exception.DimeException: User's profile couldn't be published on the di.me User Directory: Registering to /profile/@me failed.
eu.dime.commons.exception.DimeException: Failed to register at dime user register service. Aborting registration.
eu.dime.commons.exception.DimeException: User's profile couldn't be published on the di.me User Directory: Registering to /profile/@me failed.
        at eu.dime.ps.controllers.UserManagerImpl.register(UserManagerImpl.java:456)
        at eu.dime.ps.communications.requestbroker.controllers.register.PSUserController.createUser(PSUserController.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:699)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:163)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:237)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:724)
Caused by: eu.dime.commons.exception.DimeException: User's profile couldn't be published on the di.me User Directory: Registering to /profile/@me failed.
        at eu.dime.ps.controllers.UserManagerImpl.registerToUserResolverService(UserManagerImpl.java:391)
        at eu.dime.ps.controllers.UserManagerImpl.register(UserManagerImpl.java:454)
        ... 41 more
Caused by: eu.dime.ps.gateway.exception.ServiceNotAvailableException:SERV-001 - Registering to /profile/@me failed. created on:1385478683129
        at eu.dime.ps.gateway.service.external.DimeUserResolverServiceAdapter._set(DimeUserResolverServiceAdapter.java:145)
        at eu.dime.ps.gateway.service.ServiceAdapterBase.set(ServiceAdapterBase.java:214)
        at eu.dime.ps.controllers.UserManagerImpl.registerToUserResolverService(UserManagerImpl.java:385)
        ... 42 more
2013-11-26 16:11:23 PersonMatchingServiceImpl [INFO] Performed person matching for person urn:uuid:fd2a2f74-e2f2-4864-ad37-c93bd344065b [repository=7, technique=3, time=73ms]
2013-11-26 16:11:23 NotifierManagerImpl [INFO] Addind a notification in the storage:

**Comment by thielsn** [comment]
The problem turned out to be caused by using a wrong property file! :-(

The property GLOBAL_SERVER has been accidentally removed from the template file!

Please make sure to always adapt the server specific settings!

#Server specific information to be stated
GLOBAL_SERVER=localhost:8443
[...]
